---
- hosts: workers
  remote_user: ubuntu   # Using Remote user as ubuntu
  become: yes
  tasks:
  - name: Set boot cmdline
    shell: sed -i '$ s/fixrtc$/ cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1/' /boot/firmware/cmdline.txt
