#!/bin/bash

# Fetches the 'kubectl' config from the control host

declare -r CONTROL_HOST=10.0.0.80

mkdir -p ~/.kube

ssh ambrosia@${CONTROL_HOST} microk8s kubectl config view --raw | sed -e "s/127.0.0.1/${CONTROL_HOST}" > ~/.kube/config