#!/bin/bash

# AWS/EKS
#java -Dgraphics.scale=2 -Dhttps.proxy=https://${HTTPS_PROXY} -Dk8s.scalable=payment-service -Dk8s.useKubectl=false -jar podinvaders.jar

java -Dgraphics.scale=1 -Dk8s.scalable=trading-engine -Dk8s.useKubectl=false -jar podinvaders.jar